version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: <%= Rails.application.credentials.rds[:database] %>
      MYSQL_USER: <%= Rails.application.credentials.rds[:username] %>
      MYSQL_ROOT_PASSWORD: <%= Rails.application.credentials.rds[:password] %>
    tty: true
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true
  rails:
    build:
      context: .
    volumes:
      - .:/Tokai-Onair_DB
      - /Tokai-Onair_DB/node_modules
      - public-data:/Tokai-Onair_DB/public
      - tmp-data:/Tokai-Onair_DB/tmp
      - log-data:/Tokai-Onair_DB/log
    environment:
      RAILS_ENV: production
    depends_on:
      - db
    command: sh scripts/launch.sh
  nginx:
    build: 
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - rails
    volumes:
      - public-data:/Tokai-Onair_DB/public
      - tmp-data:/Tokai-Onair_DB/tmp
volumes:
  public-data:
  tmp-data:
  log-data: