version: '3'
services:
  rails:
    build:
      context: .
    volumes:
      - .:/Tokai-Onair_DB
      - /Tokai-Onair_DB/node_modules
      - public-data:/Tokai-Onair_DB/public
      - tmp-data:/Tokai-Onair_DB/tmp
      - log-data:/Tokai-Onair_DB/log
    environment:
      RAILS_ENV: production
    depends_on:
      - db
    command: sh scripts/launch.sh
  nginx:
    build: 
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - rails
    volumes:
      - public-data:/Tokai-Onair_DB/public
      - tmp-data:/Tokai-Onair_DB/tmp
volumes:
  public-data:
  tmp-data:
  log-data: